version: '3.3'

services:
  ovpn:
    image: obesbash/docker-ovpn:latest
    cap_add:
       - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    environment:
      - HOST_ADDR=<>
    ports:
      - 1194:1194/udp
      - 8099:8080/tcp
  volumes:
      - ovpn:/etc/openvpn
volumes:
  ovpn:
